[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://yael-dashboard.netlify.app"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs" 